locales:
  en:
    name: Chukchi Keyboard
    description: A test keyboard for Chukchi.
  ru:
    name: Чукотская Клавиатура
    description: Чукотская Клавиатура
author: Francis M. Tyers
email: ftyers@iu.edu
copyright: (c) 2022 Divvun/Giellatekno/UiT/Francis Tyers
organisation: UiT Norgga árktalaš universitehta
